### ISSUE TITLE
Technical aspects

### ISSUE THREAD

**Issue by Wulfheart** [Maxime-J/umami-sqlite#6]
> Moreover, SQLite has some technical aspects which don't make it a very good candidate for Umami's usage.
> _~Readme_

Hey, 

I just wanted to know what the technical aspects are that don't make it a good candidate for the usage.

**Comment by Maxime-J** [comment]
Hi,

I wrote that for multiple reasons.
But to be more clear, not being a very good candidate doesn't make it a bad solution in the end.
Just that few things have to be taken care of.

About the technical aspects:

Umami uses Prisma ORM for relational dbs, and SQLite is not totally on par feature wise with MySQL and PostgreSQL in Prisma:
createMany method isn't supported, JSON fields (used in some earlier Umami versions) aren't supported, extensions can't be loaded (we could use the uuid one).

Until recently, SQLite shipped with Prisma was lacking an interesting newest function (unixepoch).

Plus, SQLite doesn't have a storage class for dates/times,
and given Umami date functions being used, date/time storage in unixepoch format looks like the more appropriate method
but it isn't how Prisma handles dates when SQLite is used.

--

That said, it works quite well though when we circumvent all that.

Today, the only potential issue I see with my usage is the database size which could be large for not so many views, and maybe impact performance.
That's because uuids are currently stored as text, like in MySQL, and I plan to handle it #5 

Anyway, I have no experience with it but Clickhouse db seems to be the best suited solution to deal with a a large number of views/events.
