### ISSUE TITLE
Any method to migrate existing mysql db dump to a sqlite db file? 

### ISSUE THREAD

**Issue by zlwu** [Maxime-J/umami-sqlite#7]

**Comment by Maxime-J** [comment]
Just as Umami doesn't provide any method to migrate between db, I won't cover it in details.

But with a fresh Umami SQLite db and a dump (data only) from the same Umami version,
the dump would have to be reworked so that the data in prisma migrations table is left out, and all datetime fields imported as unixepoch (using SQLite unixepoch function).
